// Pure module feasibility: fake-indexeddb + real application stores/Dexie.
// Synthetic fixture/auth below exists only in this Node test, never the browser journey.
import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import { installStartupReadFault } from '../../scripts/audit-startup-read-fault.mjs';
const values = new Map<string, string>();
const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key) };
Object.assign(globalThis, { window: Object.assign(new EventTarget(), { matchMedia: () => Object.assign(new EventTarget(), { matches: false }) }), location: { origin: 'http://127.0.0.1:4173' }, localStorage: storage, sessionStorage: storage, document: { documentElement: { setAttribute: () => undefined } } });
const dbModule = await import('../../src/db/index.ts');
const session = await import('../../src/services/apiClient.ts');
const init = await import('../../src/hooks/useAppInit.ts');
const diag = await import('../../src/services/initializationDiagnostics.ts');
const settings = await import('../../src/stores/settingsStore.ts');
const sync = await import('../../src/services/syncEngine.ts');
const branch = process.argv[2] ?? 'late-recovery';
const owner = 'synthetic-startup-native-boundary';
await dbModule.bindAccountDatabase(owner);
session.setSessionActive(owner);
session.announceSessionChange();
const db = dbModule.db;
const todo = { id: 'synthetic-startup-source', text: 'Synthetic retained source', priority: 'medium' as const, done: false, completedAt: null };
await db.todos.add(todo);
await db.settings.put({ key: 'sync-version:todos:synthetic-startup-source', value: '1' });
const sourceBefore = { rows: await db.todos.toArray(), outbox: await db.outbox.toArray(), epoch: await db.settings.get('localDataEpoch') };
const priorFetch = globalThis.fetch;
const nativeTransaction = IDBDatabase.prototype.transaction;
const fakeTransport = async () => Response.json({ user: { id: owner } });
globalThis.fetch = fakeTransport;
db.close();
const fault = installStartupReadFault({ databaseName: db.name, branch });
await db.open();
const until = async (predicate: () => boolean) => { const deadline = Date.now() + 4000; while (!predicate() && Date.now() < deadline) await new Promise(resolve => setTimeout(resolve, 5)); assert.ok(predicate(), JSON.stringify(fault.snapshot())); };
const settled: Record<string, string> = {};
try {
  await fetch('/api/auth/me');
  const firstTrace = diag.beginInitializationTrace('initial');
  await settings.useSettingsStore.getState().loadSettings();
  assert.deepEqual(await sync.bootstrapSync(), { offline: true });
  const initial = init.loadAllStores(firstTrace).then(() => { settled.initial = 'success'; firstTrace.record('initialization', 'success'); }, error => { settled.initial = 'error'; firstTrace.record('initialization', 'error', error); });
  await until(() => fault.snapshot().holds.some(row => row.target === 'initial'));
  await new Promise(resolve => setTimeout(resolve, Number(process.argv[3] ?? 35)));
  assert.equal(settled.initial, undefined, 'Real explicit Dexie transaction completion remains pending');
  // This pure mechanism test does not claim the app 12s timer or browser DOM ran.
  firstTrace.record('initialization', 'timeout');
  const recoveryTrace = diag.beginInitializationTrace('recovery');
  const recovery = init.loadAllStores(recoveryTrace).then(() => { settled.recovery = 'success'; recoveryTrace.record('initialization', 'success'); }, error => { settled.recovery = 'error'; recoveryTrace.record('initialization', 'error', error); });
  await until(() => fault.snapshot().holds.some(row => row.target === 'recovery'));
  fault.finish('initial', branch === 'late-recovery' ? 'complete' : 'abort');
  await until(() => !!settled.initial);
  assert.equal(settled.initial, branch === 'late-recovery' ? 'success' : 'error');
  assert.equal(settled.recovery, undefined);
  fault.finish('recovery', 'abort');
  await Promise.all([initial, recovery]);
  assert.equal(settled.recovery, 'error');
  await until(() => fault.snapshot().holds.every(row => row.terminal));
  fault.release('explicit-test-release');
  const result = fault.snapshot();
  assert.equal(result.violation, null);
  assert.equal(result.holds.length, 2);
  assert.equal(result.initialTransactions, 1); assert.equal(result.recoveryTransactions, 1);
  assert.deepEqual(result.holds.map(row => [row.target, row.terminal]), [['initial', branch === 'late-recovery' ? 'complete' : 'abort'], ['recovery', 'abort']]);
  assert.deepEqual({ rows: await db.todos.toArray(), outbox: await db.outbox.toArray(), epoch: await db.settings.get('localDataEpoch') }, sourceBefore);
  assert.equal(globalThis.fetch, fakeTransport);
  assert.equal(IDBDatabase.prototype.transaction, nativeTransaction);
  await init.loadAllStores();
  assert.deepEqual(await db.todos.toArray(), sourceBefore.rows, 'After explicit release the real store reads the same source again');
  assert.deepEqual(await db.outbox.toArray(), []);
  assert.equal(fault.snapshot().holds.length, 2, 'Released cached Dexie method adds no new fault');
  console.log(JSON.stringify({ branch, settled, facts: result }, null, 2));
} catch (error) { console.error(JSON.stringify({ branch, settled, failure: error instanceof Error ? error.message : String(error), facts: fault.snapshot() }, null, 2)); throw error;
} finally { fault.dispose(); settings.stopPreferenceSync(); globalThis.fetch = priorFetch; db.close(); }
